### ISSUE TITLE
Please add dotnet 2.1 as we need it for openshift origin 

### ISSUE THREAD

**Issue by farshid3003** [CentOS/container-index#353] opened 2018-07-31 11:42 UTC
Please add dotnet 2.1 as we need it for openshift origin 
It is a long time that we are waiting for this image.

**Comment by mohammedzee1000** [comment] 2018-07-31 12:04
@omajid @jerboaa do you guys want to take a look at this as you maintain the dot net containers

**Comment by omajid** [comment] 2018-07-31 12:52
cc @aslicerh

Yeah, it's on our radar. I have a patch to get .NET Core 2.1 to build on CentOS. I sent it to CentOS maintainers last week. Once it's built, we definitely plan to get containers for it up and working too.

**Comment by mohammedzee1000** [comment] 2018-08-01 11:53
Thanks guys @aslicerh, i guess this yours now :)

**Comment by aslicerh** [comment] 2018-08-01 14:05
@mohammedzee1000 Yup, you can put me down for all of the dotnet containers, if I'm not already.

**Comment by mohammedzee1000** [comment] 2018-08-06 07:05
@aslicerh @farshid3003  The image builds should get done soon

**Comment by mohammedzee1000** [comment] 2018-08-06 07:45
Once someone confirms images work as expected, we can close the issue :)

**Comment by jerboaa** [comment] 2018-08-06 12:08
Looks like the build failed. `yum clean all` warning. See:
https://registry.centos.org/pipeline-logs/ZWE2MzgyZmE1Yj/

**Comment by bamachrn** [comment] 2018-08-06 13:27
@jerboaa both the build succeeded now, failure was because pipeline triggered `dotnet` image built before `runtime`. there is some issue with the cause of build. we are looking into it. thanks

**Comment by mohammedzee1000** [comment] 2018-08-06 14:33
@bamachrn thanks for updating. 
@jerboaa @farshid3003 @aslicerh, 
Can we get validation on behaviour of the image to be as expected before we close the issue.

**Comment by aslicerh** [comment] 2018-08-06 14:37
@mohammedzee1000 
Yeah, I'll test the images now.

And thanks, everyone, for your work on this.

**Comment by aslicerh** [comment] 2018-08-06 14:59
@mohammedzee1000 @farshid3003 

The images passed all our tests, so things look good from our end here.

**Comment by farshid3003** [comment] 2018-08-06 15:10
I will check it

**Comment by farshid3003** [comment] 2018-08-06 15:29
PS C:\Users\farsid.mirza\Documents\visual studio 2017\Projects\WebApplication4> docker build -t farshid3003/mytestcentosapp:latest . -f ./WebApplication4/Dockerfile
Sending build context to Docker daemon  2.488MB
Step 1/16 : FROM registry.centos.org/dotnet/dotnet-21-centos7 AS base
 ---> bf1519399fc9
Step 2/16 : WORKDIR /app
 ---> Using cache
 ---> a735395e05f6
Step 3/16 : EXPOSE 80
 ---> Using cache
 ---> bbe6c3ac1bd7
Step 4/16 : FROM registry.centos.org/dotnet/dotnet-21-runtime-centos7 AS build
 ---> ed53b4256d23
Step 5/16 : WORKDIR /src
 ---> Using cache
 ---> a17a44a3c0a5
Step 6/16 : COPY WebApplication4/WebApplication4.csproj WebApplication4/
 ---> Using cache
 ---> bc05e9eab36f
Step 7/16 : RUN dotnet restore WebApplication4/WebApplication4.csproj
 ---> Running in 5eef52017a0c
/bin/sh: dotnet: command not found
The command '/bin/sh -c dotnet restore WebApplication4/WebApplication4.csproj' returned a non-zero code: 127
PS C:\Users\farsid.mirza\Documents\visual studio 2017\Projects\WebApplication4>

**Comment by aslicerh** [comment] 2018-08-06 15:59
@farshid3003 
Dotnet is part of an scl, so it has to be enabled. The images have entrypoint and cmd steps to make that happen automatically as long as bash gets to run as normal, but the 'run' step doesn't load everything when executed like that.

You can change the step to be like:
`RUN bash -c "dotnet...`
Or
`RUN scl enable rh-dotnet21 '/bin/sh -c "dotnet...`

There are also s2i scripts built into the images, so you could build the app that way as well.

**Comment by mohammedzee1000** [comment] 2018-08-07 09:41
So i guess we are good, as we have functional dotnet 2.1 containers. Closing issue, please feel free to reopen if you think its not solved.

**Closed by mohammedzee1000** 2018-08-07 09:41 UTC
Labels: new-image
