### ISSUE TITLE
Dotnet 2.2 images

### ISSUE THREAD

**Issue by TheMidgardWatcher** [CentOS/container-index#392] opened 2019-02-11 13:01 UTC
Hi there,

It's have been passed some time from dotnet version 2.2 release, but we still have no Centos7 dotnet2.2  images to use them in our Openshift projects.

Is there any hope to expect dotnet2.2 images in regitry.centos.org soon?

**Comment by mohammedzee1000** [comment] 2019-02-11 13:33
@aslicerh PTAL

**Comment by mohammedzee1000** [comment] 2019-02-11 13:36
Index entries exist at 
https://github.com/CentOS/container-index/blob/master/index.d/dotnet.yaml#L28-L52

Yet image not in registry @bamachrn ^

**Comment by bamachrn** [comment] 2019-02-12 04:31
Looking into the same, seems there was no source change to the dotnet-22-runtime-centos7 so it was never triggered after
```
 Build #1 (Jan 11, 2019 5:43:54 AM)
OpenShift Build pipeline/dotnet-dotnet-22-runtime-centos7-latest-1 from https://github.com/redhat-developer/s2i-dotnetcore
```
and dotnet-22-centos7 is failing due to the runtime image is not present in the registry.
triggered a manual build for runtime and it fails with
```
+ docker build --no-cache --pull -t dotnet/dotnet-22-runtime-centos7:latest -f Dockerfile ./
Sending build context to Docker daemon 2.316 MB

Step 1/21 : FROM centos:7
Trying to pull repository registry.c2bf.rdu2.centos.org:5000/centos ... 
7: Pulling from registry.c2bf.rdu2.centos.org:5000/centos
e6a50b627bcb: Already exists
Digest: sha256:6c72c5194bcad7e000e14bec3f6d593a0c33100c561f40c9d2b8381e7bffbc40
Status: Downloaded newer image for registry.c2bf.rdu2.centos.org:5000/centos:7
 ---> 719ea9c10b97
Step 2/21 : EXPOSE 8080
 ---> Running in d551376c5694
 ---> 50a74529d6a3
Removing intermediate container d551376c5694
Step 3/21 : ENV HOME /opt/app-root PATH /opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DOTNET_APP_PATH /opt/app-root/app DOTNET_DATA_PATH /opt/app-root/data DOTNET_DEFAULT_CMD default-cmd.sh DOTNET_CORE_VERSION 2.2 DOTNET_FRAMEWORK netcoreapp2.2 DOTNET_RUNNING_IN_CONTAINER true DOTNET_SSL_CERT_DIR /opt/app-root/ssl_dir
 ---> Running in c1cdb2e8c908
 ---> 4213a44a67cb
Removing intermediate container c1cdb2e8c908
Step 4/21 : LABEL io.k8s.description "Platform for running .NET Core 2.2 applications" io.k8s.display-name ".NET Core 2.2" io.openshift.tags "runtime,.net,dotnet,dotnetcore,rh-dotnet22-runtime" io.openshift.expose-services "8080:http" io.openshift.s2i.scripts-url image:///usr/libexec/s2i io.s2i.scripts-url image:///usr/libexec/s2i
 ---> Running in 499e9104a80f
 ---> 5acc833bb29f
Removing intermediate container 499e9104a80f
Step 5/21 : LABEL name "dotnet/dotnet-22-runtime-centos7" com.redhat.component "rh-dotnet22-runtime-container" version "2.2" release "1" architecture "x86_64"
 ---> Running in 7a96ad5d7b9b
 ---> 17c46b6187ab
Removing intermediate container 7a96ad5d7b9b
Step 6/21 : COPY ./s2i/bin/ /usr/libexec/s2i
 ---> 4cf66b3ab53f
Removing intermediate container ab9f30fa6eba
Step 7/21 : ENV NUGET_XMLDOC_MODE skip
 ---> Running in 08f7efbee401
 ---> 5309a6a7994b
Removing intermediate container 08f7efbee401
Step 8/21 : ENV DOTNET_SKIP_FIRST_TIME_EXPERIENCE 1
 ---> Running in ed4bd9c1dd41
 ---> 2788f9e92fd1
Removing intermediate container ed4bd9c1dd41
Step 9/21 : ENV ASPNETCORE_URLS http://*:8080
 ---> Running in 9b7a81315c3f
 ---> e7a4dfe86796
Removing intermediate container 9b7a81315c3f
Step 10/21 : COPY ./contrib/ /opt/app-root
 ---> 16f47489f800
Removing intermediate container 8388566eea8f
Step 11/21 : COPY ./root/usr/bin /usr/bin
 ---> ff46edabd397
Removing intermediate container 643d490c4b55
Step 12/21 : RUN yum install -y centos-release-dotnet &&     INSTALL_PKGS="rh-dotnet22-dotnet-runtime-2.2 nss_wrapper tar unzip" &&     yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum clean all -y &&     rm -rf /var/cache/yum/*
 ---> Running in 162b62fbb7cd

[91m[0mLoaded plugins: fastestmirror, ovl
Determining fastest mirrors
Resolving Dependencies
--> Running transaction check
---> Package centos-release-dotnet.noarch 0:1-1.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package                      Arch          Version         Repository     Size
================================================================================
Installing:
 centos-release-dotnet        noarch        1-1.el7         extras        3.6 k

Transaction Summary
================================================================================
Install  1 Package

Total download size: 3.6 k
Installed size: 317  
Downloading packages:
[91mwarning: /var/cache/yum/x86_64/7/extras/packages/centos-release-dotnet-1-1.el7.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
[0mPublic key for centos-release-dotnet-1-1.el7.noarch.rpm is not installed
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
[91mImporting GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
 Package    : centos-release-7-6.1810.2.el7.centos.x86_64 (@CentOS)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
[0mRunning transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : centos-release-dotnet-1-1.el7.noarch                         1/1 
  Verifying  : centos-release-dotnet-1-1.el7.noarch                         1/1 

Installed:
  centos-release-dotnet.noarch 0:1-1.el7                                        

Complete!
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
No package rh-dotnet22-dotnet-runtime-2.2 available.
Package 2:tar-1.26-35.el7.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package nss_wrapper.x86_64 0:1.1.3-1.el7 will be installed
--> Processing Dependency: perl(strict) for package: nss_wrapper-1.1.3-1.el7.x86_64
--> Processing Dependency: perl(Getopt::Long) for package: nss_wrapper-1.1.3-1.el7.x86_64
--> Processing Dependency: perl(Cwd) for package: nss_wrapper-1.1.3-1.el7.x86_64
--> Processing Dependency: cmake for package: nss_wrapper-1.1.3-1.el7.x86_64
--> Processing Dependency: /usr/bin/perl for package: nss_wrapper-1.1.3-1.el7.x86_64
---> Package unzip.x86_64 0:6.0-19.el7 will be installed
--> Running transaction check
---> Package cmake.x86_64 0:2.8.12.2-2.el7 will be installed
--> Processing Dependency: libarchive.so.13()(64bit) for package: cmake-2.8.12.2-2.el7.x86_64
---> Package perl.x86_64 4:5.16.3-294.el7_6 will be installed
--> Processing Dependency: perl-libs = 4:5.16.3-294.el7_6 for package: 4:perl-5.16.3-294.el7_6.x86_64
--> Processing Dependency: perl(Socket) >= 1.3 for package: 4:perl-5.16.3-294.el7_6.x86_64
--> Processing Dependency: perl(Scalar::Util) >= 1.10 for package: 4:perl-5.16.3-294.el7_6.x86_64
--> Processing Dependency: perl-macros for package: 4:perl-5.16.3-294.el7_6.x86_64
--> Processing Dependency: perl-libs for package: 4:perl-5.16.3-294.el7_6.x86_64
--> Processing Dependency: perl(threads::shared) for package: 4:perl-5.16.3-294.el7_6.x86_64
--> Processing Dependency: perl(threads) for package: 4:perl-5.16.3-294.el7_6.x86_64
--> Processing Dependency: perl(constant) for package: 4:perl-5.16.3-294.el7_6.x86_64
--> Processing Dependency: perl(Time::Local) for package: 4:perl-5.16.3-294.el7_6.x86_64
--> Processing Dependency: perl(Time::HiRes) for package: 4:perl-5.16.3-294.el7_6.x86_64
--> Processing Dependency: perl(Storable) for package: 4:perl-5.16.3-294.el7_6.x86_64
--> Processing Dependency: perl(Socket) for package: 4:perl-5.16.3-294.el7_6.x86_64
--> Processing Dependency: perl(Scalar::Util) for package: 4:perl-5.16.3-294.el7_6.x86_64
--> Processing Dependency: perl(Pod::Simple::XHTML) for package: 4:perl-5.16.3-294.el7_6.x86_64
--> Processing Dependency: perl(Pod::Simple::Search) for package: 4:perl-5.16.3-294.el7_6.x86_64
--> Processing Dependency: perl(Filter::Util::Call) for package: 4:perl-5.16.3-294.el7_6.x86_64
--> Processing Dependency: perl(File::Temp) for package: 4:perl-5.16.3-294.el7_6.x86_64
--> Processing Dependency: perl(File::Path) for package: 4:perl-5.16.3-294.el7_6.x86_64
--> Processing Dependency: perl(Exporter) for package: 4:perl-5.16.3-294.el7_6.x86_64
--> Processing Dependency: perl(Carp) for package: 4:perl-5.16.3-294.el7_6.x86_64
--> Processing Dependency: libperl.so()(64bit) for package: 4:perl-5.16.3-294.el7_6.x86_64
---> Package perl-Getopt-Long.noarch 0:2.40-3.el7 will be installed
--> Processing Dependency: perl(Pod::Usage) >= 1.14 for package: perl-Getopt-Long-2.40-3.el7.noarch
--> Processing Dependency: perl(Text::ParseWords) for package: perl-Getopt-Long-2.40-3.el7.noarch
---> Package perl-PathTools.x86_64 0:3.40-5.el7 will be installed
--> Running transaction check
---> Package libarchive.x86_64 0:3.1.2-10.el7_2 will be installed
--> Processing Dependency: liblzo2.so.2()(64bit) for package: libarchive-3.1.2-10.el7_2.x86_64
---> Package perl-Carp.noarch 0:1.26-244.el7 will be installed
---> Package perl-Exporter.noarch 0:5.68-3.el7 will be installed
---> Package perl-File-Path.noarch 0:2.09-2.el7 will be installed
---> Package perl-File-Temp.noarch 0:0.23.01-3.el7 will be installed
---> Package perl-Filter.x86_64 0:1.49-3.el7 will be installed
---> Package perl-Pod-Simple.noarch 1:3.28-4.el7 will be installed
--> Processing Dependency: perl(Pod::Escapes) >= 1.04 for package: 1:perl-Pod-Simple-3.28-4.el7.noarch
--> Processing Dependency: perl(Encode) for package: 1:perl-Pod-Simple-3.28-4.el7.noarch
---> Package perl-Pod-Usage.noarch 0:1.63-3.el7 will be installed
--> Processing Dependency: perl(Pod::Text) >= 3.15 for package: perl-Pod-Usage-1.63-3.el7.noarch
--> Processing Dependency: perl-Pod-Perldoc for package: perl-Pod-Usage-1.63-3.el7.noarch
---> Package perl-Scalar-List-Utils.x86_64 0:1.27-248.el7 will be installed
---> Package perl-Socket.x86_64 0:2.010-4.el7 will be installed
---> Package perl-Storable.x86_64 0:2.45-3.el7 will be installed
---> Package perl-Text-ParseWords.noarch 0:3.29-4.el7 will be installed
---> Package perl-Time-HiRes.x86_64 4:1.9725-3.el7 will be installed
---> Package perl-Time-Local.noarch 0:1.2300-2.el7 will be installed
---> Package perl-constant.noarch 0:1.27-2.el7 will be installed
---> Package perl-libs.x86_64 4:5.16.3-294.el7_6 will be installed
---> Package perl-macros.x86_64 4:5.16.3-294.el7_6 will be installed
---> Package perl-threads.x86_64 0:1.87-4.el7 will be installed
---> Package perl-threads-shared.x86_64 0:1.43-6.el7 will be installed
--> Running transaction check
---> Package lzo.x86_64 0:2.06-8.el7 will be installed
---> Package perl-Encode.x86_64 0:2.51-7.el7 will be installed
---> Package perl-Pod-Escapes.noarch 1:1.04-294.el7_6 will be installed
---> Package perl-Pod-Perldoc.noarch 0:3.20-4.el7 will be installed
--> Processing Dependency: perl(parent) for package: perl-Pod-Perldoc-3.20-4.el7.noarch
--> Processing Dependency: perl(HTTP::Tiny) for package: perl-Pod-Perldoc-3.20-4.el7.noarch
--> Processing Dependency: groff-base for package: perl-Pod-Perldoc-3.20-4.el7.noarch
---> Package perl-podlators.noarch 0:2.5.1-3.el7 will be installed
--> Running transaction check
---> Package groff-base.x86_64 0:1.22.2-8.el7 will be installed
---> Package perl-HTTP-Tiny.noarch 0:0.033-3.el7 will be installed
---> Package perl-parent.noarch 1:0.225-244.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package                    Arch       Version                Repository   Size
================================================================================
Installing:
 nss_wrapper                x86_64     1.1.3-1.el7            dotnet       36 k
 unzip                      x86_64     6.0-19.el7             base        170 k
Installing for dependencies:
 cmake                      x86_64     2.8.12.2-2.el7         base        7.1 M
 groff-base                 x86_64     1.22.2-8.el7           base        942 k
 libarchive                 x86_64     3.1.2-10.el7_2         base        318 k
 lzo                        x86_64     2.06-8.el7             base         59 k
 perl                       x86_64     4:5.16.3-294.el7_6     updates     8.0 M
 perl-Carp                  noarch     1.26-244.el7           base         19 k
 perl-Encode                x86_64     2.51-7.el7             base        1.5 M
 perl-Exporter              noarch     5.68-3.el7             base         28 k
 perl-File-Path             noarch     2.09-2.el7             base         26 k
 perl-File-Temp             noarch     0.23.01-3.el7          base         56 k
 perl-Filter                x86_64     1.49-3.el7             base         76 k
 perl-Getopt-Long           noarch     2.40-3.el7             base         56 k
 perl-HTTP-Tiny             noarch     0.033-3.el7            base         38 k
 perl-PathTools             x86_64     3.40-5.el7             base         82 k
 perl-Pod-Escapes           noarch     1:1.04-294.el7_6       updates      51 k
 perl-Pod-Perldoc           noarch     3.20-4.el7             base         87 k
 perl-Pod-Simple            noarch     1:3.28-4.el7           base        216 k
 perl-Pod-Usage             noarch     1.63-3.el7             base         27 k
 perl-Scalar-List-Utils     x86_64     1.27-248.el7           base         36 k
 perl-Socket                x86_64     2.010-4.el7            base         49 k
 perl-Storable              x86_64     2.45-3.el7             base         77 k
 perl-Text-ParseWords       noarch     3.29-4.el7             base         14 k
 perl-Time-HiRes            x86_64     4:1.9725-3.el7         base         45 k
 perl-Time-Local            noarch     1.2300-2.el7           base         24 k
 perl-constant              noarch     1.27-2.el7             base         19 k
 perl-libs                  x86_64     4:5.16.3-294.el7_6     updates     688 k
 perl-macros                x86_64     4:5.16.3-294.el7_6     updates      44 k
 perl-parent                noarch     1:0.225-244.el7        base         12 k
 perl-podlators             noarch     2.5.1-3.el7            base        112 k
 perl-threads               x86_64     1.87-4.el7             base         49 k
 perl-threads-shared        x86_64     1.43-6.el7             base         39 k

Transaction Summary
================================================================================
Install  2 Packages (+31 Dependent packages)

Total download size: 20 M
Installed size: 68 M
Downloading packages:
--------------------------------------------------------------------------------
Total                                               39 MB/s |  20 MB  00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : groff-base-1.22.2-8.el7.x86_64                              1/33 
  Installing : 1:perl-parent-0.225-244.el7.noarch                          2/33 
  Installing : perl-HTTP-Tiny-0.033-3.el7.noarch                           3/33 
  Installing : perl-podlators-2.5.1-3.el7.noarch                           4/33 
  Installing : perl-Pod-Perldoc-3.20-4.el7.noarch                          5/33 
  Installing : 1:perl-Pod-Escapes-1.04-294.el7_6.noarch                    6/33 
  Installing : perl-Text-ParseWords-3.29-4.el7.noarch                      7/33 
  Installing : perl-Encode-2.51-7.el7.x86_64                               8/33 
  Installing : perl-Pod-Usage-1.63-3.el7.noarch                            9/33 
  Installing : 4:perl-libs-5.16.3-294.el7_6.x86_64                        10/33 
  Installing : 4:perl-macros-5.16.3-294.el7_6.x86_64                      11/33 
  Installing : perl-threads-1.87-4.el7.x86_64                             12/33 
  Installing : perl-Storable-2.45-3.el7.x86_64                            13/33 
  Installing : perl-Exporter-5.68-3.el7.noarch                            14/33 
  Installing : perl-constant-1.27-2.el7.noarch                            15/33 
  Installing : perl-Time-Local-1.2300-2.el7.noarch                        16/33 
  Installing : perl-Socket-2.010-4.el7.x86_64                             17/33 
  Installing : perl-Carp-1.26-244.el7.noarch                              18/33 
  Installing : 4:perl-Time-HiRes-1.9725-3.el7.x86_64                      19/33 
  Installing : perl-threads-shared-1.43-6.el7.x86_64                      20/33 
  Installing : perl-PathTools-3.40-5.el7.x86_64                           21/33 
  Installing : perl-Scalar-List-Utils-1.27-248.el7.x86_64                 22/33 
  Installing : perl-File-Temp-0.23.01-3.el7.noarch                        23/33 
  Installing : perl-File-Path-2.09-2.el7.noarch                           24/33 
  Installing : perl-Filter-1.49-3.el7.x86_64                              25/33 
  Installing : 1:perl-Pod-Simple-3.28-4.el7.noarch                        26/33 
  Installing : perl-Getopt-Long-2.40-3.el7.noarch                         27/33 
  Installing : 4:perl-5.16.3-294.el7_6.x86_64                             28/33 
  Installing : lzo-2.06-8.el7.x86_64                                      29/33 
  Installing : libarchive-3.1.2-10.el7_2.x86_64                           30/33 
  Installing : cmake-2.8.12.2-2.el7.x86_64                                31/33 
  Installing : nss_wrapper-1.1.3-1.el7.x86_64                             32/33 
  Installing : unzip-6.0-19.el7.x86_64                                    33/33 
  Verifying  : perl-HTTP-Tiny-0.033-3.el7.noarch                           1/33 
  Verifying  : perl-threads-shared-1.43-6.el7.x86_64                       2/33 
  Verifying  : perl-Storable-2.45-3.el7.x86_64                             3/33 
  Verifying  : 1:perl-Pod-Escapes-1.04-294.el7_6.noarch                    4/33 
  Verifying  : perl-threads-1.87-4.el7.x86_64                              5/33 
  Verifying  : perl-Exporter-5.68-3.el7.noarch                             6/33 
  Verifying  : perl-constant-1.27-2.el7.noarch                             7/33 
  Verifying  : perl-PathTools-3.40-5.el7.x86_64                            8/33 
  Verifying  : lzo-2.06-8.el7.x86_64                                       9/33 
  Verifying  : 1:perl-parent-0.225-244.el7.noarch                         10/33 
  Verifying  : 4:perl-5.16.3-294.el7_6.x86_64                             11/33 
  Verifying  : libarchive-3.1.2-10.el7_2.x86_64                           12/33 
  Verifying  : perl-Pod-Usage-1.63-3.el7.noarch                           13/33 
  Verifying  : 4:perl-libs-5.16.3-294.el7_6.x86_64                        14/33 
  Verifying  : groff-base-1.22.2-8.el7.x86_64                             15/33 
  Verifying  : perl-File-Temp-0.23.01-3.el7.noarch                        16/33 
  Verifying  : 1:perl-Pod-Simple-3.28-4.el7.noarch                        17/33 
  Verifying  : perl-Time-Local-1.2300-2.el7.noarch                        18/33 
  Verifying  : 4:perl-macros-5.16.3-294.el7_6.x86_64                      19/33 
  Verifying  : perl-Socket-2.010-4.el7.x86_64                             20/33 
  Verifying  : perl-Carp-1.26-244.el7.noarch                              21/33 
  Verifying  : 4:perl-Time-HiRes-1.9725-3.el7.x86_64                      22/33 
  Verifying  : perl-Scalar-List-Utils-1.27-248.el7.x86_64                 23/33 
  Verifying  : nss_wrapper-1.1.3-1.el7.x86_64                             24/33 
  Verifying  : perl-Encode-2.51-7.el7.x86_64                              25/33 
  Verifying  : perl-Pod-Perldoc-3.20-4.el7.noarch                         26/33 
  Verifying  : perl-podlators-2.5.1-3.el7.noarch                          27/33 
  Verifying  : perl-File-Path-2.09-2.el7.noarch                           28/33 
  Verifying  : cmake-2.8.12.2-2.el7.x86_64                                29/33 
  Verifying  : perl-Filter-1.49-3.el7.x86_64                              30/33 
  Verifying  : perl-Getopt-Long-2.40-3.el7.noarch                         31/33 
  Verifying  : perl-Text-ParseWords-3.29-4.el7.noarch                     32/33 
  Verifying  : unzip-6.0-19.el7.x86_64                                    33/33 

Installed:
  nss_wrapper.x86_64 0:1.1.3-1.el7           unzip.x86_64 0:6.0-19.el7          

Dependency Installed:
  cmake.x86_64 0:2.8.12.2-2.el7                                                 
  groff-base.x86_64 0:1.22.2-8.el7                                              
  libarchive.x86_64 0:3.1.2-10.el7_2                                            
  lzo.x86_64 0:2.06-8.el7                                                       
  perl.x86_64 4:5.16.3-294.el7_6                                                
  perl-Carp.noarch 0:1.26-244.el7                                               
  perl-Encode.x86_64 0:2.51-7.el7                                               
  perl-Exporter.noarch 0:5.68-3.el7                                             
  perl-File-Path.noarch 0:2.09-2.el7                                            
  perl-File-Temp.noarch 0:0.23.01-3.el7                                         
  perl-Filter.x86_64 0:1.49-3.el7                                               
  perl-Getopt-Long.noarch 0:2.40-3.el7                                          
  perl-HTTP-Tiny.noarch 0:0.033-3.el7                                           
  perl-PathTools.x86_64 0:3.40-5.el7                                            
  perl-Pod-Escapes.noarch 1:1.04-294.el7_6                                      
  perl-Pod-Perldoc.noarch 0:3.20-4.el7                                          
  perl-Pod-Simple.noarch 1:3.28-4.el7                                           
  perl-Pod-Usage.noarch 0:1.63-3.el7                                            
  perl-Scalar-List-Utils.x86_64 0:1.27-248.el7                                  
  perl-Socket.x86_64 0:2.010-4.el7                                              
  perl-Storable.x86_64 0:2.45-3.el7                                             
  perl-Text-ParseWords.noarch 0:3.29-4.el7                                      
  perl-Time-HiRes.x86_64 4:1.9725-3.el7                                         
  perl-Time-Local.noarch 0:1.2300-2.el7                                         
  perl-constant.noarch 0:1.27-2.el7                                             
  perl-libs.x86_64 4:5.16.3-294.el7_6                                           
  perl-macros.x86_64 4:5.16.3-294.el7_6                                         
  perl-parent.noarch 1:0.225-244.el7                                            
  perl-podlators.noarch 0:2.5.1-3.el7                                           
  perl-threads.x86_64 0:1.87-4.el7                                              
  perl-threads-shared.x86_64 0:1.43-6.el7                                       

Complete!
package rh-dotnet22-dotnet-runtime-2.2 is not installed
The command '/bin/sh -c yum install -y centos-release-dotnet &&     INSTALL_PKGS="rh-dotnet22-dotnet-runtime-2.2 nss_wrapper tar unzip" &&     yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum clean all -y &&     rm -rf /var/cache/yum/*' returned a non-zero code: 1
```

@TheMidgardWatcher could you please look into this. we are working to get logs visible to UI by this week. so you can always check the logs.

**Comment by TheMidgardWatcher** [comment] 2019-02-12 11:41
@bamachrn Sorry, I don't really expert in images building, but I've asked for help in Source-to-Image repo. Hope somebody could help...

**Comment by TheMidgardWatcher** [comment] 2019-02-12 11:48
@bamachrn By the way, where did you trigger this build? Maybe if I'll see whole process I'll find somebody to ask from my colleagues, who knows OpenShift better than me

**Comment by bamachrn** [comment] 2019-02-12 12:00
@TheMidgardWatcher Builds runs on the Container-pipeline-service which is backend for https://registry.centos.org. It seems the issue is `No package rh-dotnet22-dotnet-runtime-2.2 available.`
there is no package available in the repo.

**Comment by TheMidgardWatcher** [comment] 2019-02-12 12:06
@aslicerh Could you please give more details on this?

**Comment by aslicerh** [comment] 2019-02-13 15:00
@TheMidgardWatcher @bamachrn 
This was talked about a couple of weeks ago. We put in the changes to have the 2.2 containers built without realizing that no one has produced the actual RPMs yet. From what I understand, the source code for building the RPMs is available and ready (and has been for quite a while now), it's just that no one has gotten around to actually producing packages yet.

I asked around on IRC and sent out a few emails trying to determine what the expected date for those packages are, but all I was able to get was that the team was aware of the availability of the source.

**Comment by TheMidgardWatcher** [comment] 2019-02-14 12:28
@aslicerh So, as i understood - there is some maintainers of this packages but they don't want to build and push version 2.2 or am i missing something?

**Comment by TheMidgardWatcher** [comment] 2019-02-20 09:09
@aslicerh What could we do to have this packages built?

**Comment by aslicerh** [comment] 2019-02-20 15:36
@TheMidgardWatcher @bamachrn 
Hopefully everything will be ready soon. We finally got in touch with the right people to get this produced. Sorry it took this long!

**Comment by bamachrn** [comment] 2019-02-21 09:33
@aslicerh @TheMidgardWatcher images are built successfully and available to pull, would be available after sometime in https://registry.centos.org UI. please have a look at the images.

**Comment by TheMidgardWatcher** [comment] 2019-02-21 17:50
@bamachrn all is working now! Thanks guys for such a great help!

**Comment by bamachrn** [comment] 2019-02-22 04:35
ACK, closing this

**Closed by bamachrn** 2019-02-22 04:35 UTC
